# Generated by Django 5.2.17 on 2026-09-26 02:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArquivoGuardado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="tabela")),
                (
                    "registro",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="registro"
                    ),
                ),
                ("campo", models.CharField(max_length=100, verbose_name="campo")),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="nome original"),
                ),
                ("tipo", models.CharField(max_length=100, verbose_name="tipo")),
                ("tamanho", models.BigIntegerField(verbose_name="tamanho (bytes)")),
                (
                    "caminho",
                    models.CharField(max_length=255, verbose_name="onde está guardado"),
                ),
                (
                    "espaco",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="espaço (cota)",
                    ),
                ),
                (
                    "enviado_por",
                    models.CharField(max_length=254, verbose_name="enviado por"),
                ),
                (
                    "enviado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado em"),
                ),
            ],
            options={
                "verbose_name": "arquivo guardado",
                "verbose_name_plural": "arquivos guardados",
                "indexes": [
                    models.Index(
                        fields=["modelo", "registro"],
                        name="infra_vibec_modelo_201fb1_idx",
                    )
                ],
            },
        ),
    ]
