# Generated by Django 5.2.17 on 2026-09-26 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_vibecoding", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arquivoguardado",
            name="publico",
            field=models.BooleanField(default=False, verbose_name="público"),
        ),
        migrations.CreateModel(
            name="LinkDeCompartilhamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resumo",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="resumo do código",
                    ),
                ),
                (
                    "criado_por",
                    models.CharField(max_length=254, verbose_name="criado por"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                ("vence_em", models.DateTimeField(verbose_name="vence em")),
                (
                    "cancelado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelado em"
                    ),
                ),
                (
                    "cancelado_por",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="cancelado por"
                    ),
                ),
                (
                    "downloads",
                    models.PositiveIntegerField(default=0, verbose_name="downloads"),
                ),
                (
                    "ultimo_download_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último download em"
                    ),
                ),
                (
                    "arquivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="infra_vibecoding.arquivoguardado",
                        verbose_name="arquivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "link de compartilhamento",
                "verbose_name_plural": "links de compartilhamento",
                "ordering": ["-criado_em"],
            },
        ),
    ]
