# Generated by Django 5.2.17 on 2026-09-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_vibecoding", "0002_compartilhamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quando",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="quando"
                    ),
                ),
                (
                    "pedido",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        verbose_name="código do pedido",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        verbose_name="pessoa logada",
                    ),
                ),
                ("autor", models.CharField(max_length=254, verbose_name="quem gravou")),
                (
                    "como_sistema",
                    models.BooleanField(default=False, verbose_name="como sistema"),
                ),
                ("motivo", models.TextField(blank=True, verbose_name="motivo")),
                ("tabela", models.CharField(max_length=100, verbose_name="tabela")),
                ("registro", models.CharField(max_length=64, verbose_name="registro")),
                (
                    "rotulo",
                    models.CharField(blank=True, max_length=200, verbose_name="rótulo"),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criou", "criou"),
                            ("alterou", "alterou"),
                            ("excluiu", "excluiu"),
                            ("acao", "ação"),
                        ],
                        max_length=10,
                        verbose_name="ação",
                    ),
                ),
                (
                    "nome_da_acao",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nome da ação"
                    ),
                ),
                (
                    "mudancas",
                    models.JSONField(blank=True, default=dict, verbose_name="mudanças"),
                ),
            ],
            options={
                "verbose_name": "histórico",
                "verbose_name_plural": "histórico",
                "ordering": ["-quando", "-id"],
                "indexes": [
                    models.Index(
                        fields=["tabela", "registro"],
                        name="infra_vibec_tabela_568582_idx",
                    )
                ],
            },
        ),
    ]
