# Generated by Django 5.2.17 on 2026-09-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_vibecoding", "0003_historico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quando",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="quando"
                    ),
                ),
                (
                    "pedido",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=16,
                        verbose_name="código do pedido",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrou", "entrou"),
                            ("senha_errada", "senha errada"),
                            ("bloqueado", "bloqueado"),
                            ("saiu", "saiu"),
                            ("negado", "acesso negado"),
                            ("dois_fatores", "verificação em duas etapas"),
                            ("senha", "senha"),
                            ("link", "link de acesso"),
                            ("download", "download"),
                            ("planilha", "planilha"),
                            ("tela_de_banco", "tela de banco"),
                            ("erro", "erro"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "pessoa",
                    models.CharField(
                        blank=True, db_index=True, max_length=254, verbose_name="pessoa"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="endereço de internet"
                    ),
                ),
                (
                    "navegador",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="navegador"
                    ),
                ),
                (
                    "tela",
                    models.CharField(blank=True, max_length=300, verbose_name="tela"),
                ),
                (
                    "detalhe",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="detalhe"
                    ),
                ),
            ],
            options={
                "verbose_name": "registro",
                "verbose_name_plural": "registros",
                "ordering": ["-quando", "-id"],
            },
        ),
    ]
